language: dart

os:
 - linux
 - osx

dart:
 - stable
 - dev

dart_task:
 - test: --platform vm
 - dartanalyzer: --fatal-warnings lib
 - dartfmt

branches:
  only: [master]

cache:
  directories:
    - $HOME/.pub-cache