language: dart

os:
 - linux
 - osx
 - windows

dart:
 - stable

before_script:
 - dart example/download_chromium.dart

dart_task:
 - test: --platform vm
 - dartanalyzer: --fatal-infos --fatal-warnings .
 - dartfmt

jobs:
 include:
  - stage: coverage
    script:
     # Ne pas utiliser dart_coveralls mais simplement "coverage" et utiliser
     # un gem coveralls plus stable (https://github.com/dart-lang/coverage/blob/master/.travis.yml)
     - pub global activate dart_coveralls
     - dart tool/generate_all_tests_file.dart
     - dart_coveralls report test/_all_tests.dart

branches:
  only: [master]

env:
  global:
    #In travis/docker we need the --no-sandbox flag in chrome
    - CHROME_FORCE_NO_SANDBOX=true

cache:
  directories:
    - $HOME/.pub-cache
