language: dart

os:
 - linux
 - osx

dart:
 - stable
 - dev

dart_task:
# TODO(xha): remove --concurrency=1 whe we have a proper locking mecanism
 - test: --platform vm --concurrency=1
 - dartanalyzer: --fatal-warnings lib
 - dartfmt

branches:
  only: [master]

cache:
  directories:
    - $HOME/.pub-cache