language: dart

os:
 - linux
 - osx

dart:
 - stable
 - dev

dart_task:
# TODO(xha): remove --concurrency=1 once we have a proper locking mecanism
 - test: --platform vm --concurrency=1
 - dartanalyzer: --fatal-infos --fatal-warnings .
 - dartfmt

branches:
  only: [master]

env:
  global:
    #In travis/docker we need the --no-sandbox flag in chrome
    - CHROME_FORCE_NO_SANDBOX=true

cache:
  directories:
    - $HOME/.pub-cache