include: package:pedantic/analysis_options.yaml
analyzer:
 strong-mode:
  implicit-casts: false
linter:
 rules:
  omit_local_variable_types: false
  empty_statements: true
  hash_and_equals: true
  iterable_contains_unrelated_type: true
  list_remove_unrelated_type: true
  no_adjacent_strings_in_list: true
  test_types_in_equals: true
  unnecessary_statements: true
  avoid_setters_without_getters: true
  avoid_void_async: true
  await_only_futures: true
  camel_case_types: true
  constant_identifier_names: true
  non_constant_identifier_names: true
  only_throw_errors: true
  overridden_fields: true
  prefer_inlined_adds: true
  prefer_interpolation_to_compose_strings: true
  prefer_null_aware_operators: true
  prefer_typing_uninitialized_variables: true
  unnecessary_brace_in_string_interps: true
  unnecessary_getters_setters: true
  unnecessary_parenthesis: true
  void_checks: true
  sort_pub_dependencies: true
