include: package:pedantic/analysis_options.yaml
linter:
 rules:
  - empty_statements
  - hash_and_equals
  - iterable_contains_unrelated_type
  - list_remove_unrelated_type
  - no_adjacent_strings_in_list
  - test_types_in_equals
  - unnecessary_statements
  - annotate_overrides
  - avoid_setters_without_getters
  - avoid_void_async
  - await_only_futures
  - camel_case_types
  - constant_identifier_names
  - non_constant_identifier_names
  - only_throw_errors
  - overridden_fields
  - prefer_adjacent_string_concatenation
  - prefer_collection_literals
  - prefer_conditional_assignment
  - prefer_generic_function_type_aliases
  - prefer_inlined_adds
  - prefer_interpolation_to_compose_strings
  - prefer_iterable_whereType
  - prefer_null_aware_operators
  - prefer_spread_collections
  - prefer_typing_uninitialized_variables
  - unnecessary_brace_in_string_interps
  - unnecessary_getters_setters
  - unnecessary_const
  - unnecessary_new
  - unnecessary_parenthesis
  - unnecessary_this
  - use_function_type_syntax_for_parameters
  - void_checks
  - sort_pub_dependencies
