name: puppeteer
description: A high-level API to control headless Chrome over the DevTools Protocol. This is a port of Puppeteer in Dart.
version: 1.23.0-nullsafety.0
homepage: https://github.com/xvrh/puppeteer-dart

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  archive: ^3.0.0
  async: ^2.5.0
  collection: ^1.15.0
  http: ^0.13.0
  logging: ^1.0.0
  meta: ^1.3.0
  path: ^1.8.0
  petitparser: ^4.0.0-nullsafety.1
  pool: ^1.5.0

dev_dependencies:
  analyzer: ^0.41.0
  build: ^1.5.1
  build_runner: ^1.10.6
  crypto: ^3.0.0
  dart_style: ^1.3.6
  image: ^3.0.0-nullsafety.0
  json_annotation: ^4.0.0-nullsafety.0
  json_serializable: ^4.0.0-nullsafety.0
  pedantic: ^1.10.0
  shelf: ^1.0.0
  shelf_static: ^0.2.7
  test: ^1.16.0
  yaml: ^3.0.0

dependency_overrides:
  shelf_static:
    git:
      url: https://github.com/xvrh/shelf_static.git
      ref: null-safety
