name: puppeteer
description: A high-level API to control headless Chrome over the DevTools Protocol. This is a port of Puppeteer in Dart.
version: 1.16.1
homepage: https://github.com/xvrh/puppeteer-dart

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  archive: ^2.0.0
  async: ^2.2.0
  collection: ^1.14.0
  http: '>=0.9.0 <0.13.0'
  logging: ^0.11.3
  meta: ^1.1.1
  mime: ^0.9.0
  path: '>=1.0.0 <2.0.0'
  petitparser: '>=2.2.0 <4.0.0'
  pool: ^1.4.0

dev_dependencies:
  analyzer:
  build_runner: ^1.0.0
  crypto:
  dart_style: ^1.2.7
  image: ^2.1.3
  json_annotation: ^2.0.0
  json_serializable: ^2.0.0
  pedantic: ^1.9.0
  shelf: ^0.7.2
  shelf_static: ^0.2.7
  test:
  yaml:
