name: chrome_dev_tools
description: A client of the DevTools Protocol to automate a Headless Chrome browser. This is an alternative to Puppeteer in Dart.
version: 2.0.0-dev
homepage: https://github.com/xavierhainaux/chrome_dev_tools
author: Xavier Hainaux <xavier.hainaux@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  archive: ^2.0.0
  http: '>=0.9.0 <0.13.0'
  logging: ^0.11.3
  meta: ^1.1.1
  path: '>=1.0.0 <2.0.0'
  pool: ^1.4.0

dev_dependencies:
  dart_style: ^1.1.0
  shelf: ^0.7.2
  shelf_static: ^0.2.7
  test:
